[workspace]
members = ["protos"]

[package]
name = "versioning-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
protos = { path = "protos" }
tonic = "0.11.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.86"
tonic-reflection = "0.11.0"
