[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"   # or the version you are using
prost = "0.11"  # or the version you are using

[build-dependencies]
tonic-build = "0.9"  # or the version you are using