[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11.0"   # or the version you are using
prost = "0.12.6"

[build-dependencies]
tonic-build = "0.11.0"  # or the version you are using